# Using `ascii_binder` gem with `jruby-gradle-plugin`

This is a
http://sscce.org/[Short, Self Contained, Correct (Compilable) Example]
or
https://stackoverflow.com/help/mcve[Minimal, Complete, and Verifiable example]
project for working through issues using the `ascii_binder` gem with the `jruby-gradle-plugin`.

After cloning this project, if you execute:

* `./gradlew printSomePrettyOutputPlease`

the first time you will see the following error
[source,bash]
.Error output
----
...
Building native extensions.  This could take a while...
ERROR:  Error installing /$HOME/.gradle/caches/modules-2/files-2.1/rubygems/yajl-ruby/1.3.1/f7c94882c4600a78aaaf81f04a217ccd969a714c/yajl-ruby-1.3.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
/usr/lib/jvm/jdk1.8.0_152/jre/bin/java -cp :$HOME/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.1.7.0/d6b98ab4b7d9ad305e3331eca5528bd03960cf76/jruby-complete-9.1.7.0.jar org.jruby.Main -r ./siteconf20180827-19436-505lg5.rb extconf.rb
creating Makefile

current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
make "DESTDIR=" clean
Makefile:225: *** multiple target patterns.  Stop.

current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
make "DESTDIR="
Makefile:225: *** multiple target patterns.  Stop.

make failed, exit code 2

Gem files will remain installed in $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1 for inspection.
Results logged to $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/extensions/universal-java-1.8/2.3.0/yajl-ruby-1.3.1/gem_make.out
...
----

However, the second time, you will get the standard http://jruby-gradle.org/[JRuby-Gradle] Quick Start output.

If you execute:

* `./gradlew asciiBinder`

you will get the following error:

[source,bash]
.Error output
----
> Task :asciiBinder FAILED
Gem::MissingSpecError: Gem::MissingSpecError
                        to_specs at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency.rb:308
  block in activate_dependencies at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1439
                            each at org/jruby/RubyArray.java:1733
           activate_dependencies at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1428
                        activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1410
                    try_activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:220
                         require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:125
                          <main> at $HOME/Projects/gradleAsciiBinder/src/docs/asciidoc/asciiBinder.rb:2
...
----

If you install a Ruby environment before executing the following to install the `ascii_binder` gem and run the script outside of the `jruby-gradle-plugin`:

* `gem install ascii_binder`
* `./src/docs/asciidoc/asciiBinder.rb`

then you'll receive the following output:

[source,bash]
.Success output
----
Input:
Output:
AsciiBinder: v0.1.15.1
----

At this point, I'm just trying to determine if it is viable to use the `ascii_binder` gem with the `jruby-gradle-plugin`.
